language: ruby
rvm:
  - 2.2
  - jruby
  - 2.0.0-p247
dist: trusty
script:
  - chmod +x ./_build/deploy.sh
  - chmod +x ./_build/build.sh
  - ./_build/build.sh
  - ./_build/deploy.sh > /dev/null
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify?secret=helloworld
